from typing import Any, Protocol, Dict


class Repository(Protocol):
    async def get_by_options(
        self, schema: Any, eager: bool = False
    ) -> Dict[str, Any]: ...

    async def get_by_id(self, id: Any, eager: bool = False) -> Any: ...

    async def create(self, schema: Any) -> Any: ...

    async def update(self, id: Any, schema: Any) -> Any: ...

    async def update_attr(self, id: Any, column: str, value: Any) -> Any: ...

    async def whole_update(self, id: Any, schema: Any) -> Any: ...

    async def delete_by_id(self, id: Any) -> None: ...
