image: { repository: ghcr.io/your-org/qdic-assets, tag: latest, pullPolicy: Always }
env:
  CONTROLLER_URL: "http://qdic-controller:8080"
  DATABASE_URL: "postgresql+asyncpg://assets:password@postgres.tenant:5432/assets"
  RABBITMQ_URL: "amqp://user:pass@rabbitmq.tenant:5672/"
  OPENSEARCH_URL: "http://opensearch.tenant:9200"
  ADVERTISE_ENDPOINT: ""
service: { type: ClusterIP, port: 8080 }
resources: { requests: { cpu: 200m, memory: 256Mi }, limits: { cpu: 1, memory: 1Gi } }
debezium:
  enabled: true
  image: quay.io/debezium/server:3.1
  postgres:
    host: "postgres.tenant"
    port: 5432
    db: "poc"
    user: "debezium"
    password: "debeziumpass"
    slot: "app_cdc_slot"
    publication: "events_publication"
    table_include_list: "public.events"
  rabbitmq:
    host: "rabbitmq.tenant"
    port: 5672
    username: "user"
    password: "pass"
    exchange: "debezium"
    routingKey: "app.public.events"
    vhost: "/tenant"
