"""Migration

Revision ID: 7dd8d518a253
Revises: 
Create Date: 2025-09-25 20:58:52.012474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd8d518a253'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('authority_user_group_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_groups_id'), 'asset_groups', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('comment_on_ddl', sa.String(), nullable=True),
    sa.Column('ddl_statement', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_csv_imported', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_lost', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('logical_name', sa.String(), nullable=True),
    sa.Column('physical_name', sa.String(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('record_updated_at', sa.String(), nullable=True),
    sa.Column('ext_url', sa.String(), nullable=True),
    sa.Column('ext_access_count', sa.BigInteger(), nullable=True),
    sa.Column('ext_name', sa.String(), nullable=True),
    sa.Column('ext_description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('data_sharing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sharing_name', sa.String(), nullable=True),
    sa.Column('physical_name', sa.String(), nullable=True),
    sa.Column('sharing_type', sa.String(), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sharing_id'), 'data_sharing', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('is_fast_track', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('wait_time', sa.Integer(), nullable=True),
    sa.Column('is_dependency_resolved', sa.Boolean(), nullable=True),
    sa.Column('completed_in_seconds', sa.BigInteger(), nullable=True),
    sa.Column('receipt_handle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('ext_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('possible_global_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ext_table_name', sa.String(), nullable=True),
    sa.Column('ext_table_name_path', sa.String(), nullable=True),
    sa.Column('ext_description', sa.String(), nullable=True),
    sa.Column('ext_service_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_connections_id'), 'ext_connections', ['id'], unique=False)
    op.create_table('ext_owners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_owners_id'), 'ext_owners', ['id'], unique=False)
    op.create_table('ext_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_sources_id'), 'ext_sources', ['id'], unique=False)
    op.create_table('ext_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ext_tag_description', sa.String(), nullable=True),
    sa.Column('ext_tag_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_tags_id'), 'ext_tags', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('values', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('property_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_sets_id'), 'property_sets', ['id'], unique=False)
    op.create_table('tag_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_groups_id'), 'tag_groups', ['id'], unique=False)
    op.create_table('asset_asset_group',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('asset_group_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'asset_group_id')
    )
    op.create_table('asset_data_sharing',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('data_sharing_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['data_sharing_id'], ['data_sharing.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'data_sharing_id')
    )
    op.create_table('asset_ext_connections',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ext_connection_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ext_connection_id'], ['ext_connections.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'ext_connection_id')
    )
    op.create_table('asset_ext_owners',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ext_owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ext_owner_id'], ['ext_owners.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'ext_owner_id')
    )
    op.create_table('asset_ext_tags',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ext_tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ext_tag_id'], ['ext_tags.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'ext_tag_id')
    )
    op.create_table('asset_paths',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ancestor_id', sa.String(), nullable=False),
    sa.Column('ancestor_name', sa.String(), nullable=False),
    sa.Column('ancestor_type', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('path_order', sa.Integer(), nullable=True),
    sa.Column('path_layer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'ancestor_id'),
    sa.UniqueConstraint('asset_id', 'path_order', name='uq_asset_path_order')
    )
    op.create_index('ix_asset_paths_ancestor_id', 'asset_paths', ['ancestor_id'], unique=False)
    op.create_index('ix_asset_paths_asset_id_depth', 'asset_paths', ['asset_id', 'depth'], unique=False)
    op.create_table('asset_property_sets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('property_set_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['property_set_id'], ['property_sets.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'property_set_id')
    )
    op.create_table('asset_relationships',
    sa.Column('parent_asset_id', sa.String(), nullable=False),
    sa.Column('child_asset_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_asset_id', 'child_asset_id')
    )
    op.create_table('ext_connection_sources',
    sa.Column('ext_connection_id', sa.String(), nullable=False),
    sa.Column('ext_source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ext_connection_id'], ['ext_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ext_source_id'], ['ext_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ext_connection_id', 'ext_source_id')
    )
    op.create_index('ix_ext_conn_source_conn', 'ext_connection_sources', ['ext_connection_id'], unique=False)
    op.create_index('ix_ext_conn_source_src', 'ext_connection_sources', ['ext_source_id'], unique=False)
    op.create_table('lineages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=False),
    sa.Column('parent_asset_id', sa.String(), nullable=True),
    sa.Column('target_asset_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lineage_source_target', 'lineages', ['source_asset_id', 'target_asset_id'], unique=False)
    op.create_table('property_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_set_property',
    sa.Column('property_set_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['property_set_id'], ['property_sets.id'], ),
    sa.PrimaryKeyConstraint('property_set_id', 'property_id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stats_size', sa.Float(), nullable=True),
    sa.Column('stats_count', sa.BigInteger(), nullable=True),
    sa.Column('stats_max', sa.String(), nullable=True),
    sa.Column('stats_min', sa.String(), nullable=True),
    sa.Column('stats_mean', sa.String(), nullable=True),
    sa.Column('stats_median', sa.String(), nullable=True),
    sa.Column('stats_mode', sa.String(), nullable=True),
    sa.Column('stats_stddev', sa.String(), nullable=True),
    sa.Column('stats_number_of_null', sa.BigInteger(), nullable=True),
    sa.Column('stats_number_of_unique', sa.BigInteger(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_group_id', sa.String(), nullable=False),
    sa.Column('parent_tag_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('asset_tag_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('child_tag_id', sa.String(), nullable=True),
    sa.Column('parent_tag_id', sa.String(), nullable=True),
    sa.Column('tag_group_id', sa.String(), nullable=True),
    sa.Column('link_type', sa.Enum('manual', 'rule', name='link_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'parent_tag_id', 'child_tag_id', name='uq_asset_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_tag_links')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_table('property_set_property')
    op.drop_table('property_attachments')
    op.drop_index('idx_lineage_source_target', table_name='lineages')
    op.drop_table('lineages')
    op.drop_index('ix_ext_conn_source_src', table_name='ext_connection_sources')
    op.drop_index('ix_ext_conn_source_conn', table_name='ext_connection_sources')
    op.drop_table('ext_connection_sources')
    op.drop_table('asset_relationships')
    op.drop_table('asset_property_sets')
    op.drop_index('ix_asset_paths_asset_id_depth', table_name='asset_paths')
    op.drop_index('ix_asset_paths_ancestor_id', table_name='asset_paths')
    op.drop_table('asset_paths')
    op.drop_table('asset_ext_tags')
    op.drop_table('asset_ext_owners')
    op.drop_table('asset_ext_connections')
    op.drop_table('asset_data_sharing')
    op.drop_table('asset_asset_group')
    op.drop_index(op.f('ix_tag_groups_id'), table_name='tag_groups')
    op.drop_table('tag_groups')
    op.drop_index(op.f('ix_property_sets_id'), table_name='property_sets')
    op.drop_table('property_sets')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_ext_tags_id'), table_name='ext_tags')
    op.drop_table('ext_tags')
    op.drop_index(op.f('ix_ext_sources_id'), table_name='ext_sources')
    op.drop_table('ext_sources')
    op.drop_index(op.f('ix_ext_owners_id'), table_name='ext_owners')
    op.drop_table('ext_owners')
    op.drop_index(op.f('ix_ext_connections_id'), table_name='ext_connections')
    op.drop_table('ext_connections')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_data_sharing_id'), table_name='data_sharing')
    op.drop_table('data_sharing')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_groups_id'), table_name='asset_groups')
    op.drop_table('asset_groups')
    # ### end Alembic commands ###
